name: Cypress training CI

on: push

jobs:
  browser-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: "slawekradzyminski/awesome-localstack"
          path: "awesome-localstack"
      - name: Run Docker Compose
        run: |
          cd awesome-localstack
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh
      - run: npm install
      - name: Setup Browser
        uses: browser-actions/setup-${{ matrix.browser }}@v1
      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}